name: Pipelines

on: 
  push:
    branches:
      - 'main'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Using Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependecies
        run: npm ci

      - name: Check
        run: |
          npm run typecheck
          npm run lint

      - name: Test
        run: npm run test

      - name: Build
        env:
          CI: false
        run: npm run build